FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y build-essential git cmake software-properties-common \
                       zlib1g-dev libevent-dev

RUN add-apt-repository ppa:gophers/archive && \
    apt-get update && \
    apt-get install -y golang-1.9-go && \
    cp /usr/lib/go-1.9/bin/go* /usr/bin/.

RUN mkdir /src
WORKDIR /src

RUN mkdir /src/lsquic
RUN git clone -b v4.0.6 https://github.com/litespeedtech/lsquic.git /src/lsquic && \
    cd /src/lsquic && \
    git submodule update --init && \
    cd /src

RUN git clone https://boringssl.googlesource.com/boringssl && \
    cd boringssl && \
    git checkout a2278d4d2cabe73f6663e3299ea7808edfa306b9 && \
    cmake . && \
    make

RUN cd /src/lsquic && \
    cmake -DBORINGSSL_DIR=/src/boringssl . && \
    make

RUN mkdir /lsquic_bin

RUN cd lsquic && cp bin/http_client /lsquic_bin && cp bin/http_server /lsquic_bin

COPY ./lsquic.crt /
COPY ./lsquic.key /

WORKDIR /lsquic_bin

CMD [ "./http_server -c localhost.com,/lsquic.crt,/lsquic.key -L debug -s 0.0.0.0:4433  -Q h3" ]